### ISSUE TITLE
`master` contains a single failing test

### ISSUE THREAD

**Issue by drahnr** [paritytech/sccache#72]
rev `a70346110554f9f37601b9dcc1e19a3e71ede889` fails consistently for me with one test case:

```
RUST_BACKTRACE=1 cargo t
    Finished test [unoptimized + debuginfo] target(s) in 0.12s
     Running target/debug/deps/sccache-c934d896e3f03b6e

running 208 tests
test azure::blobstore::test::test_put_blob ... ignored
test azure::credentials::test::test_parse_connection_string ... ok
test azure::credentials::test::test_conn_str_with_endpoint_suffix_only ... ok
test azure::blobstore::test::test_canonicalize_resource ... ok
test azure::credentials::test::test_parse_connection_string_without_account_key ... ok
test azure::blobstore::test::test_signing ... ok
test compiler::args::tests::assert_tests::test_args_iter_no_conflict ... ok
test compiler::args::tests::test_arginfo_cmp ... ok
test compiler::args::tests::test_arginfo_process_take_concat_arg_delim_doesnt_crash ... ok
test compiler::args::tests::test_arginfo_process ... ok
test compiler::args::tests::test_multi_search ... ok
test compiler::args::tests::test_bsearch ... ok
test compiler::args::tests::test_argument_into_iter ... ok
test compiler::args::tests::test_argsiter ... ok
test compiler::c::test::test_extra_hash_data ... ok
test compiler::c::test::test_hash_key_args_differs ... ok
test compiler::c::test::test_hash_key_preprocessed_content_differs ... ok
test compiler::c::test::test_plusplus_differs ... ok
test compiler::c::test::test_same_content ... ok
test compiler::c::test::test_hash_key_executable_contents_differs ... ok
test compiler::c::test::test_hash_key_env_var_differs ... ok
test compiler::clang::test::test_parse_arguments_clangmodules ... ok
test compiler::clang::test::test_parse_arguments_simple ... ok
test compiler::clang::test::test_parse_arguments_values ... ok
test compiler::clang::test::test_parse_arguments_others ... ok
test compiler::clang::test::test_parse_fsanitize_blacklist ... ok
test compiler::clang::test::test_parse_fplugin ... ok
test compiler::clang::test::test_parse_xclang_add_plugin ... ok
test compiler::clang::test::test_parse_color_diags ... ok
test compiler::clang::test::test_parse_xclang_llvm_stuff ... ok
test compiler::clang::test::test_parse_xclang_load ... ok
test compiler::clang::test::test_parse_xclang_invalid ... ok
test compiler::clang::test::test_parse_xclang_verify ... ok
test compiler::clang::test::test_parse_xclang_plugin_arg_find_bad_constructs ... ok
test compiler::clang::test::test_parse_xclang_plugin_arg_blink_gc_plugin ... ok
test compiler::compiler::test::test_compiler_version_affects_hash ... ok
test compiler::compiler::test::test_compiler_get_cached_or_compile_preprocessor_error ... ok
test compiler::compiler::test::test_detect_compiler_kind_clang ... ok
test compiler::compiler::test::test_detect_compiler_kind_diab ... ok
test compiler::compiler::test::test_compiler_get_cached_or_compile ... ok
test compiler::compiler::test::test_compiler_get_cached_or_compile_force_recache ... ok
test compiler::compiler::test::test_detect_compiler_kind_gcc ... ok
test compiler::compiler::test::test_compiler_get_cached_or_compile_cache_error ... ok
test compiler::compiler::test::test_detect_compiler_kind_msvc ... ok
test compiler::compiler::test::test_detect_compiler_kind_process_fail ... ok
test compiler::diab::test::test_at_signs ... ok
test compiler::compiler::test::test_detect_compiler_kind_unknown ... ok
test compiler::diab::test::test_at_signs_file ... ok
test compiler::diab::test::test_at_signs_file_not_readable ... ok
test compiler::compiler::test::test_compiler_get_cached_or_compile_dist ... ok
test compiler::diab::test::test_parse_arguments_default_name ... ok
test compiler::diab::test::test_parse_arguments_empty_args ... ok
test compiler::diab::test::test_parse_arguments_extra ... ok
test compiler::diab::test::test_parse_arguments_link ... ok
test compiler::diab::test::test_parse_arguments_not_compile ... ok
test compiler::diab::test::test_parse_arguments_simple ... ok
test compiler::diab::test::test_parse_arguments_preprocessor_args ... ok
test compiler::diab::test::test_compile_simple ... ok
test compiler::diab::test::test_parse_arguments_values ... ok
test compiler::diab::test::test_parse_dry_run ... ok
test compiler::compiler::test::test_detect_compiler_kind_nvcc ... ok
test compiler::diab::test::test_parse_arguments_too_many_inputs ... ok
test compiler::gcc::test::color_mode_preprocess ... ok
test compiler::compiler::test::test_get_compiler_info ... ok
test compiler::gcc::test::test_parse_arguments_coverage_outputs_gcno ... ok
test compiler::gcc::test::test_parse_arguments_default_name ... ok
test compiler::gcc::test::test_parse_arguments_default_outputdir ... ok
test compiler::gcc::test::test_parse_arguments_dep_target_needed ... ok
test compiler::gcc::test::test_parse_arguments_empty_args ... ok
test compiler::compiler::test::test_compiler_get_cached_or_compile_dist_error ... ok
test compiler::gcc::test::test_parse_arguments_diagnostics_color ... ok
test compiler::gcc::test::test_parse_arguments_explicit_dep_target ... ok
test compiler::gcc::test::test_parse_arguments_explicit_dep_target_needed ... ok
test compiler::gcc::test::test_parse_arguments_explicit_mq_dep_target_needed ... ok
test compiler::gcc::test::test_parse_arguments_extra ... ok
test compiler::gcc::test::test_parse_arguments_link ... ok
test compiler::gcc::test::test_parse_arguments_linker_options ... ok
test compiler::gcc::test::test_parse_arguments_not_compile ... ok
test compiler::gcc::test::test_parse_arguments_pgo ... ok
test compiler::gcc::test::test_parse_arguments_plusplus ... ok
test compiler::gcc::test::test_parse_arguments_multiple_arch ... ok
test compiler::gcc::test::test_parse_arguments_profile_generate ... ok
test compiler::gcc::test::test_parse_arguments_response_file ... ok
test compiler::gcc::test::test_parse_arguments_preprocessor_args ... ok
test compiler::gcc::test::test_parse_arguments_simple ... ok
test compiler::gcc::test::test_parse_arguments_split_dwarf ... ok
test compiler::gcc::test::test_parse_arguments_test_coverage_outputs_gcno ... ok
test compiler::gcc::test::test_parse_arguments_too_many_inputs ... ok
test compiler::gcc::test::test_parse_arguments_values ... ok
test compiler::msvc::test::parse_argument_slashes ... ok
test compiler::msvc::test::test_parse_arguments_clang_passthrough ... ok
test compiler::msvc::test::test_parse_arguments_default_name ... ok
test compiler::msvc::test::test_parse_arguments_empty_args ... ok
test compiler::msvc::test::test_parse_arguments_external_include ... ok
test compiler::msvc::test::test_parse_arguments_extra ... ok
test compiler::msvc::test::test_parse_arguments_missing_edit_and_continue_pdb ... ok
test compiler::gcc::test::at_signs ... ok
test compiler::compiler::test::test_detect_compiler_kind_rustc ... ok
test compiler::msvc::test::test_parse_arguments_not_compile ... ok
test compiler::msvc::test::test_parse_arguments_missing_pdb ... ok
test compiler::msvc::test::test_compile_not_cacheable_pdb ... ok
test compiler::msvc::test::test_compile_simple ... ok
test compiler::msvc::test::test_parse_arguments_passthrough ... ok
test compiler::gcc::test::test_compile_simple ... ok
test compiler::msvc::test::test_parse_arguments_pdb ... ok
test compiler::msvc::test::test_parse_arguments_response_file ... ok
test compiler::msvc::test::test_parse_arguments_too_many_inputs ... ok
test compiler::msvc::test::test_parse_arguments_simple ... ok
test compiler::msvc::test::test_parse_arguments_values ... ok
test compiler::msvc::test::test_parse_compile_flag ... ok
test compiler::msvc::test::test_detect_showincludes_prefix ... ok
test compiler::msvc::test::test_parse_arguments_unsupported ... ok
test compiler::nvcc::test::test_parse_arguments_dc_compile_flag ... ok
test compiler::nvcc::test::test_parse_arguments_simple_c ... ok
test compiler::msvc::test::test_parse_fsanitize_blacklist ... ok
test compiler::nvcc::test::test_parse_arguments_simple_cu ... ok
test compiler::nvcc::test::test_parse_arguments_simple_c_as_cu ... ok
test compiler::nvcc::test::test_parse_cant_cache_flags ... ok
test compiler::nvcc::test::test_parse_arguments_values ... ok
test compiler::nvcc::test::test_parse_dlink_is_not_compilation ... ok
test compiler::nvcc::test::test_parse_generate_code_flags ... ok
test compiler::nvcc::test::test_parse_no_capturing_of_xcompiler ... ok
test compiler::nvcc::test::test_parse_md_mt_flags_cu ... ok
test compiler::nvcc::test::test_parse_pass_to_host_flags ... ok
test compiler::rust::test::test_get_compiler_outputs ... ok
test compiler::rust::test::test_get_compiler_outputs_fail ... ok
test compiler::rust::test::test_parse_arguments_dep_info_no_extra_filename ... ok
test compiler::rust::test::test_parse_arguments_color ... ok
test compiler::rust::test::test_parse_arguments_incremental ... ok
test compiler::rust::test::test_parse_arguments_native_libs ... ok
test cache::gcs::test_gcs_credential_provider ... ok
test compiler::rust::test::test_parse_arguments_non_rlib_crate ... ok
test compiler::rust::test::test_parse_dep_info ... ok
test compiler::rust::test::test_parse_dep_info_abs_paths ... ok
test compiler::rust::test::test_parse_dep_info_cwd ... ok
test compiler::rust::test::test_parse_rustc_z_ls ... ok
test compiler::rust::test::test_parse_dep_info_with_escaped_spaces ... ok
test compiler::rust::test::test_generate_hash_key ... ok
test config::config_overrides ... ok
test config::test_gcs_credentials_url ... ok
test compiler::rust::test::test_parse_arguments_simple ... ok
test dist::cache::client::test::test_client_toolchains_custom ... ok
test dist::cache::client::test::test_client_toolchains_custom_multiuse_archive ... ok
test compiler::rust::test::test_equal_hashes_cfg_features ... ok
test compiler::rust::test::test_equal_hashes_ignored_args ... ok
test compiler::rust::test::test_equal_hashes_link_paths ... ok
test dist::cache::client::test::test_client_toolchains_custom_nodist_conflict ... ok
test dist::cache::client::test::test_client_toolchains_nodist ... ok
test dist::pkg::toolchain_imp::test_ldd_parse_static ... ok
test config::full_toml_parse ... ok
test dist::pkg::toolchain_imp::test_ldd_parse ... ok
test lru_disk_cache::lru_cache::tests::test_change_capacity ... ok
test lru_disk_cache::lru_cache::tests::test_clear ... ok
test lru_disk_cache::lru_cache::tests::test_contains_key ... ok
test lru_disk_cache::lru_cache::tests::test_debug ... ok
test dist::pkg::toolchain_imp::test_ldd_parse_v2_30 ... ok
test lru_disk_cache::lru_cache::tests::test_expire_lru ... ok
test compiler::rust::test::test_equal_hashes_externs ... ok
test lru_disk_cache::lru_cache::tests::test_iter ... ok
test lru_disk_cache::lru_cache::tests::test_metered_cache ... ok
test lru_disk_cache::lru_cache::tests::test_metered_cache_oversize ... ok
test lru_disk_cache::lru_cache::tests::test_metered_cache_reinsert_larger ... ok
test lru_disk_cache::lru_cache::tests::test_pop ... ok
test lru_disk_cache::lru_cache::tests::test_put_and_get ... ok
test lru_disk_cache::lru_cache::tests::test_put_update ... ok
test lru_disk_cache::lru_cache::tests::test_remove ... ok
test lru_disk_cache::tests::test_empty_dir ... ok
test lru_disk_cache::tests::test_existing_file_too_large ... ok
test lru_disk_cache::tests::test_existing_files_lru_mtime ... ok
test lru_disk_cache::tests::test_insert_bytes_exact ... ok
test lru_disk_cache::tests::test_add_get_lru ... ok
test lru_disk_cache::tests::test_insert_bytes ... ok
test lru_disk_cache::tests::test_missing_root ... ok
test lru_disk_cache::tests::test_insert_file ... ok
test lru_disk_cache::tests::test_insert_bytes_too_large ... ok
test lru_disk_cache::tests::test_remove ... ok
test lru_disk_cache::tests::test_some_existing_files ... ok
test mock_command::test::test_mock_command_output ... ok
test mock_command::test::test_mock_command_sync ... ok
test mock_command::test::test_mock_command_calls ... ok
test server::waits_until_zero ... ok
test mock_command::test::test_mock_command_wait ... ok
test mock_command::test::test_mock_spawn_error ... ok
test simples3::s3::test::test_signature ... ok
test mock_command::test::test_mock_wait_error ... ok
test config::test_parse_size ... ok
test test::tests::test_server_shutdown_no_idle ... ok
test test::tests::test_server_stats ... ok
test test::tests::test_server_shutdown ... ok
test test::utils::test_map_contains_ok ... ok
test test::tests::test_server_idle_timeout ... ok
test util::tests::simple_starts_with ... ok
test util::tests::simple_strip_prefix ... ok
test test::tests::test_server_unsupported_compiler ... ok
test test::tests::test_server_compile ... ok
test test::tests::test_server_port_in_use ... ok
test compiler::args::tests::assert_tests::test_arginfo_process_take_arg ... ok
test compiler::args::tests::assert_tests::test_arginfo_process_flag ... ok
test compiler::args::tests::assert_tests::test_arginfo_process_take_concat_arg ... ok
test compiler::args::tests::assert_tests::test_arginfo_process_take_concat_arg_delim ... ok
test compiler::args::tests::assert_tests::test_arginfo_process_take_maybe_concat_arg ... ok
test compiler::args::tests::assert_tests::test_arginfo_process_take_maybe_concat_arg_delim ... ok
test compiler::args::tests::assert_tests::test_args_iter_unsorted ... ok
test compiler::args::tests::assert_tests::test_args_iter_unsorted_2 ... ok
test mock_command::test::test_unexpected_new_command ... ok
test test::utils::test_map_contains_extra_key ... ok
test test::utils::test_map_contains_missing_key ... ok
test test::utils::test_map_contains_wrong_value ... ok

test result: ok. 207 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.10s

     Running target/debug/deps/sccache-5ce6ba2ad4c9faca

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/dist-ee5256fcfe905656

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/oauth-196bcafff12aeff6

running 1 test
test test_auth ... ignored

test result: ok. 0 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running target/debug/deps/sccache_cargo-8d71709abea60091

running 1 test
test test_rust_cargo ... FAILED

failures:

---- test_rust_cargo stdout ----
thread 'test_rust_cargo' panicked at 'Unexpected stdout, failed var.contains("\"cache_hits\":{\"counts\":{\"Rust\":2}}")
└── var as str: 

command=`"/media/supersonic1t/projects/sccache/target/debug/sccache" "--show-stats" "--stats-format=json"`
code=2
stdout=``````
stderr=```sccache: error: failed to get stats from server
sccache: caused by: Failed to send data to or receive data from server
sccache: caused by: Failed to read response header
sccache: caused by: failed to fill whole buffer
```
', /home/bernhard/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.2/src/assert.rs:348:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:435:5
   2: assert_cmd::assert::Assert::stdout_impl
             at /home/bernhard/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.2/src/assert.rs:348:17
   3: assert_cmd::assert::Assert::stdout
             at /home/bernhard/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.2/src/assert.rs:341:9
   4: sccache_cargo::test_rust_cargo_cmd
             at ./tests/sccache_cargo.rs:124:5
   5: sccache_cargo::test_rust_cargo
             at ./tests/sccache_cargo.rs:17:5
   6: sccache_cargo::test_rust_cargo::{{closure}}
             at ./tests/sccache_cargo.rs:16:1
   7: core::ops::function::FnOnce::call_once
             at /home/bernhard/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   8: core::ops::function::FnOnce::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

failures:
    test_rust_cargo

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.39s

error: test failed, to rerun pass '--test sccache_cargo'
```

**Comment by Xanewok** [comment]
Unfortunately, I can't reproduce this locally (Ubuntu 20.10).

Can you try running `sccache --stop-server`? The test suite should do it automatically, but maybe this helps...
Which `SCCACHE_*` env vars are present in your environment? Can you reproduce this using some older commits, e.g. before `std::future::Future` migration PR was merged?
